/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#00101c",
        "surface-container-high": "#1b2c39",
        "surface-container-highest": "#263645",
        "surface-dim": "#041522",
        "on-tertiary-fixed-variant": "#321ed2",
        "on-tertiary-fixed": "#0f0069",
        "on-secondary": "#003642",
        "on-secondary-fixed": "#001f27",
        "surface-tint": "#b0c6ff",
        "on-surface-variant": "#c2c6d7",
        "inverse-on-surface": "#223240",
        "on-surface": "#d3e4f7",
        "secondary-fixed": "#b4ebff",
        "on-tertiary-container": "#fffdff",
        "on-primary-container": "#fffdff",
        "primary": "#b0c6ff",
        "surface-container": "#10212f",
        "surface-variant": "#263645",
        "on-primary-fixed": "#001945",
        "on-primary": "#002d6f",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#0058cb",
        "inverse-surface": "#d3e4f7",
        "tertiary": "#c3c0ff",
        "on-primary-fixed-variant": "#00429c",
        "outline": "#8c90a0",
        "tertiary-container": "#655dff",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "on-tertiary": "#1d00a5",
        "on-secondary-fixed-variant": "#004e5f",
        "surface": "#041522",
        "outline-variant": "#424655",
        "secondary": "#a2e7ff",
        "primary-container": "#146ef5",
        "background": "#041522",
        "on-secondary-container": "#005669",
        "surface-bright": "#2b3b49",
        "secondary-fixed-dim": "#3cd7ff",
        "surface-container-low": "#0c1d2a",
        "primary-fixed-dim": "#b0c6ff",
        "tertiary-fixed-dim": "#c3c0ff",
        "on-background": "#d3e4f7",
        "secondary-container": "#00d2fd",
        "tertiary-fixed": "#e2dfff",
        "error-container": "#93000a",
        "primary-fixed": "#d9e2ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "container-max": "1280px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
